services:
  redis:
    image: redis:7-alpine
    container_name: currency-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: go-currency-tracker
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379 
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # веб-интерфейс Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app